# Travis CI

before_script:
  - chmod +x script/cibuild
  - chmod +x script/bootstrap
  - chmod +x script/branding
  - chmod +x script/cibuild
  - chmod +x script/console
  - chmod +x script/cucumber
  - chmod +x script/proof
  - chmod +x script/rubyprof
  - chmod +x script/stackprof
  - chmod +x script/test
  - chmod +x script/travis
  - chmod +x script/vendor-mimes
  - gem update --system
  - gem install bundler
  - bundle update

bundler_args: --without benchmark:site:development

script: script/cibuild

cache: bundler

language: ruby

sudo: false

rvm:
  - &ruby1 2.3.0
  - &ruby2 2.2.4
  - &ruby3 2.1.8
  - &jruby jruby-9.0.4.0
  - &rhead ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: *jruby
    - rvm: *rhead
env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber

branches:
  only:
    - ruby

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e6011bb9dce6d5c0753
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com
