markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

##gauges_id: 
##google_analytics_id: UA-
##google_site_verification: 

repository: https://github.com/bunto/bunto
help_url: https://github.com/bunto/bunto-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true

name: Bunto
description: Transform your plain text into static websites and web application framework
url: https://bunto.github.io

twitter:
  username: buntorb

logo: img/logo-2x.png

gems:
  - bunto-feed
  - bunto-redirect-from
  - bemoji
  - bunto-sitemap
  - bunto-seo-tag
  - bunto-avatar
