markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-XXXX

repository: https://github.com/bunto/bunto
help_url: https://github.com/bunto/help

collections:
  docs:
    output: true
