markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

##gauges_id: 
##google_analytics_id: UA-
##google_site_verification: 

repository: https://github.com/bunto/bunto
help_url: https://github.com/bunto/bunto-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true

name: Bunto • Simple, WAF-aware, static sites
description: Transform your plain text into static websites and web application framework
url: https://bunto.github.io

twitter:
  username: buntowaf

logo: img/logo-2x.png

gems:
  - bunto-feed
  - bunto-redirect-from
  - bemoji
  - bunto-sitemap
  - bunto-seo-tag
  - bunto-avatar
  - bunto-mentions
